package templates

import (
	"crypto/rand"
	"encoding/base32"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/goccy/go-yaml"

	"github.com/jekyo/jekyo/internal/dsl"
)

// Meta is the lenient view of a template file: enough to list, inspect,
// and resolve it without tripping strict validation or interpolation.
type Meta struct {
	App         string               `yaml:"app"`
	Description string               `yaml:"description"`
	Icon        string               `yaml:"icon"`
	Inputs      map[string]dsl.Input `yaml:"inputs"`
}

// ParseMeta reads template metadata leniently.
func ParseMeta(data []byte) (Meta, error) {
	var m Meta
	if err := yaml.Unmarshal(data, &m); err != nil {
		return Meta{}, fmt.Errorf("template: %w", err)
	}
	return m, nil
}

var inputNameRe = regexp.MustCompile(`^[A-Z][A-Z0-9_]*$`)

// Resolution is the outcome of resolving a template's inputs.
type Resolution struct {
	// Values substitute ${NAME} directly in the written jekyo.yaml.
	Values map[string]string
	// Secrets go to .env; the yaml keeps ${NAME} references.
	Secrets map[string]string
}

// PromptFunc asks the user for one input; returning "" accepts the default
// (or requests generation for secrets).
type PromptFunc func(name string, in dsl.Input) (string, error)

// Resolve computes values for every input. set provides explicit values
// (--set); useDefaults accepts defaults without prompting; prompt may be
// nil for fully non-interactive resolution. Missing required inputs are
// returned as an error listing all of them.
func Resolve(inputs map[string]dsl.Input, set map[string]string, useDefaults bool, prompt PromptFunc) (Resolution, error) {
	res := Resolution{Values: map[string]string{}, Secrets: map[string]string{}}
	var missing []string

	for _, name := range sortedInputNames(inputs) {
		in := inputs[name]
		if !inputNameRe.MatchString(name) {
			return res, fmt.Errorf("template input %q: names must be UPPER_SNAKE_CASE (they are ${VAR} references)", name)
		}
		val, provided := set[name]
		if !provided && !useDefaults && prompt != nil {
			answered, err := prompt(name, in)
			if err != nil {
				return res, err
			}
			if answered != "" {
				val, provided = answered, true
			}
		}
		if !provided {
			switch {
			case in.Kind == "secret":
				gen, err := newSecret()
				if err != nil {
					return res, err
				}
				val = gen
			case in.Default != "":
				val = in.Default
			case in.IsRequired():
				missing = append(missing, name)
				continue
			}
		}
		if in.Kind == "secret" {
			res.Secrets[name] = val
		} else {
			res.Values[name] = val
		}
	}
	if len(missing) > 0 {
		return res, fmt.Errorf("missing required inputs: %s (pass them with --set NAME=value; see 'jekyo templates inspect')", strings.Join(missing, ", "))
	}
	return res, nil
}

// Apply substitutes resolved values into the template text, strips the
// inputs: block, and returns the final jekyo.yaml plus the .env content
// (empty when there are no secrets).
func Apply(template []byte, res Resolution) (yamlOut []byte, envOut []byte) {
	out := string(template)
	for name, val := range res.Values {
		out = strings.ReplaceAll(out, "${"+name+"}", val)
	}
	out = stripTopLevelBlock(out, "inputs")

	if len(res.Secrets) == 0 {
		return []byte(out), nil
	}
	var env strings.Builder
	env.WriteString("# Generated by jekyo init — referenced as ${VAR} from jekyo.yaml.\n# Keep out of version control.\n")
	for _, name := range sortedKeys(res.Secrets) {
		fmt.Fprintf(&env, "%s=%s\n", name, res.Secrets[name])
	}
	return []byte(out), []byte(env.String())
}

// stripTopLevelBlock removes a top-level YAML key and its indented body.
func stripTopLevelBlock(s, key string) string {
	lines := strings.Split(s, "\n")
	var out []string
	skipping := false
	for _, l := range lines {
		if strings.HasPrefix(l, key+":") {
			skipping = true
			continue
		}
		if skipping {
			if l == "" || strings.HasPrefix(l, " ") || strings.HasPrefix(l, "\t") || strings.HasPrefix(l, "#") {
				continue
			}
			skipping = false
		}
		out = append(out, l)
	}
	return strings.Join(out, "\n")
}

func newSecret() (string, error) {
	raw := make([]byte, 15)
	if _, err := rand.Read(raw); err != nil {
		return "", err
	}
	return base32.StdEncoding.WithPadding(base32.NoPadding).EncodeToString(raw), nil
}

func sortedInputNames(m map[string]dsl.Input) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
